# Generated by Django 6.1 on 2026-08-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_chatmessage_conversation_delete_todoitem_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='todo_chatme_convers_61a040_idx'),
        ),
    ]
